# Generated by Django 5.0.4 on 2024-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_book_fine_remove_book_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
